languageCode = "pt-br"
languageName = "Português Brasileiro"
displayName = "PT-BR"
isoCode = "pt-br"
weight = 1
rtl = false

title = "Blog do Prof"
# logo = "img/logo.png"
description = "Kotlin, Golang e outras coisa interessantes"
copyright = "Bruno Lopes - 2023"

dateFormat = "2 January 2006"

[author]
  name = "Bruno Lopes"
  image = "img/bruno.png"
  headline = "Kotlin, Golang, Linux e outras coisitas mas que me de vontade de escrever!"
  bio = "Atua na área de educação de TI, experiência como professor universitário, streamer na Twitch, podcaster, mestre em ciência da computação, bacharel em sistemas de informação"
  links = [
    { email = "contato@profbrunolopes.dev.br" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/brunolopesjn" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
    { instagram = "https://instagram.com/brunolopesjn" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/profbrunolopes" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
    { telegram = "https://t.me/profbrunolopes" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
    { twitch = "https://twitch.tv/profburnolopes" },
    { twitter = "https://twitter.com/profbrunolopes" },
  #   { whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://youtube.com/brunolopesjn" },
  ]
