baseURL = "http://brunolopesjn.dev.br/"
theme = "LoveIt"
title = "Blog do Prof"
languageCode = "pt-br"
languageName = "Português"
defaultContentLanguage = "pt-br"
hasCJKLanguage = false

[author]
  name = "Bruno Lopes"
  email = "brunolopesjn@gmail.com"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Postagens"
    url = "/posts/"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    name = "Categorias"
    url = "/categories/"

[params.header.title]
  name = "Blog do Prof"

[params.app]
  title = "Blog do Prof"
  noFavicon = false

[params.home]
  rss = 10

[params.home.profile]
  enable = true
  gravatarEmail = "brunolopesjn@gmail.com"
  title = "Blog do Prof"
  subtitle = "Kotlin, Golang e outras coisas que achar interessantes!"

[params.home.posts]
  enable = true
  paginate = 10

[params.social]
  GitHub = "brunolopesjn"
  Linkedin = "profbrunolopes/"
  Twitter = "profbrunolopes"
  Instagram = "brunolopesjn"
  Telegram = "profbrunolopes"
  Youtubechannel = ""
  Twitch = "profbrunolopes"
  Mastodon = "https://bolha.us/@profbrunolopes"
  Email = "brunolopesjn@gmail.com"
  RSS = true

[params.page.share]
  enable = true
  Twitter = true
  Linkedin = true
  Whatsapp = true
  HackerNews = true
  Reddit = true
  Weibo = true
  Blogger = true
  Baidu = true

[params.page.comment]
  enable = true
[params.page.comment.disqus]
  enable = true
  shortname = "https-profbrunolopes-dev-br.disqus.com"

[markup]
  [markup.highlight]
    noClasses = false
